### ISSUE TITLE
nix-build -A nix-linter fails

### ISSUE THREAD

**Issue by ryantm** [Synthetica9/nix-linter#9] opened 2018-11-22 00:50 UTC
Hello.

I'm trying to use nix-linter in a project and I'm trying to import it into the project. I ran into an issue building it.

I found that nix-shell works fine for me but

```shell
$ nix-build -A nix-linter
....
building '/nix/store/lw6vnw8fn87c0fywry53c1pls83azyhk-nix-linter-0.1.0.0.drv'...                                                                       
setupCompilerEnvironmentPhase                                                                                                                          
Build with /nix/store/n5i1zdpmk2b1s3z96649xh8f9kr3g96s-ghc-8.4.3.                                                                                      
ignoring (possibly broken) abi-depends field for packages                                                                                              
ignoring (possibly broken) abi-depends field for packages                                                                                              
unpacking sources                                                                                                                                      
unpacking source archive /nix/store/h12xgnwdp3dprki01lqjd169z1p07xsm-1jn0k4x8gr4232gfjr58z8fmavl9hkz0-source                                           
source root is 1jn0k4x8gr4232gfjr58z8fmavl9hkz0-source                                                                                                 
patching sources                                                                                                                                       
compileBuildDriverPhase                                                                                                                                
setupCompileFlags: -package-db=/build/setup-package.conf.d -j1 -threaded                                                                               
[1 of 1] Compiling Main             ( Setup.hs, /build/Main.o )                                                                                        
Linking Setup ...                                                                                                                                      
configuring                                                                                                                                            
configureFlags: --verbose --prefix=/nix/store/50fwiywz5w1890hdxxmg2qmksc99l1x7-nix-linter-0.1.0.0 --libdir=$prefix/lib/$compiler --libsubdir=$abi/$lib\
name --docdir=/nix/store/3njik1kp7kfm7dwpc7xdb7m662jn2z4r-nix-linter-0.1.0.0-doc/share/doc/nix-linter-0.1.0.0 --with-gcc=gcc --package-db=/build/packa\
ge.conf.d --ghc-option=-j1 --disable-split-objs --enable-library-profiling --profiling-detail=exported-functions --disable-profiling --enable-shared -\
-disable-coverage --enable-static --disable-executable-dynamic --enable-tests --enable-library-vanilla --enable-library-for-ghci --ghc-option=-split-s\
ections --extra-lib-dirs=/nix/store/s2n99784krxl91mfw3cnn9ylbb5fjvkx-ncurses-6.1/lib --extra-lib-dirs=/nix/store/rxaclc3vhxbzgfllv7601i85z854h48a-gmp-\
6.1.2/lib                                                                                                                                              
Using Parsec parser                                                                                                                                    
Configuring nix-linter-0.1.0.0...                                                                                                                      
CallStack (from HasCallStack):                                                                                                                         
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:958:20 in Cabal-2.2.0.1:Distribution.Simple.Configure                         
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:462:12 in Cabal-2.2.0.1:Distribution.Simple.Configure    
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:596:20 in Cabal-2.2.0.1:Distribution.Simple                                        
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.2.0.1:Distribution.Simple.UserHooks                       
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:178:19 in Cabal-2.2.0.1:Distribution.Simple                                  
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:115:27 in Cabal-2.2.0.1:Distribution.Simple                                
  defaultMain, called at Setup.hs:2:8 in main:Main                                                                                                     
Setup: Encountered missing dependencies:                                                                                                               
aeson >=1.4, containers >=0.6 
```

Do you have any suggestions for how to build it as a derivation outside of `shellFor`?

Thanks,
Ryan

**Comment by Synthetica9** [comment] 2018-11-22 14:11
I haven't needed to do that yet, so it's not something I regularly test. (I should probably setup some form of CI.)

After some experimenting, the root cause seems to be that Nixpkgs ships an old version of Aeson and Containers, but nix-linter works fine with those versions as well.

**Comment by Synthetica9** [comment] 2018-11-22 14:12
(Feel free to re-open this if you are still experiencing issues, but it's fixed On My End:tm: )

**Closed** 2018-11-22 14:11 UTC

**Comment by ryantm** [comment] 2018-11-26 21:12
It works for me too!
